# Generated by Django 3.2.23 on 2024-08-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('PIZZA', 'PIZZA'), ('DRINKS', 'DRINKS')], default='PIZZA', max_length=20),
        ),
    ]
